Dawalton/readmelint
Azure-Samples/Microchip-PIC-IoT-Wx pull request #4
Opened 2020-08-20 17:26 UTC by danewalton

Using [this VSCode markdown extension](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one):
- Add table of contents
- Fix linter issues to play nice with the table of contents (which gets autogenerated based on headings)

2020-08-20 17:49 UTC, jasmineymlo reviewed
Thanks for adding the ToC and fixed formatting.  LGTM.  Please check with Quinn to make sure she is ok before merging the changes.

2020-08-20 17:49 UTC, jasmineymlo commented on README.md
> +# Microchip-PIC24-IoT-Wx
The name of the board is PIC-IoT-Wx where x could be G or A.
https://www.microchip.com/developmenttools/ProductDetails/AC164164

2020-08-21 07:35 UTC, nkhuyent requested changes

2020-08-21 07:35 UTC, nkhuyent commented on README.md
> +- For the Plug and Play sample, download the Plug and Play DTMI [here](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/samples/Thermostat.json)
Let's be consistent with guidance from feature team to use "IoT Plug and Play" through our the doc. 

FYI - usage guidance:
**First use:** IoT Plug and Play 
**Second and subsequent use**: IoT Plug and Play
**Don’t use**: “IoT Plug & Play”, “Azure Plug and Play”, “IoT PnP”, “Plug and Play”, or any other variation including an ampersand (&)

2020-08-21 07:35 UTC, nkhuyent commented on README.md
> +## Prerequisites
My proposal - let us 
1) remove this "Prerequisites" session since this overlap with the "Setup Instructions" (I'll make sure move the installation of Azure IoT Explorer from the "View PIC-IoT board telemetry on Azure IoT Explorer" section up to this "Setup Instructions" as well. 
2) I'll rename the existing "Setup Instructions" into "Prerequisites" as well to make sure folks done with this step before moving forward.

what do you think?

2020-08-21 07:35 UTC, nkhuyent commented on README.md
> +Once the board is flashed (directions later), you can proceed to interact with the Plug and Play device using the Azure IoT Explorer. The following steps make it as seamless as possible.
What do you mean by "directions later"? Are you saying that you will add the detailed instruction on how to flashed the board later?

2020-08-21 07:35 UTC, nkhuyent commented on README.md
> +
Could you add a brief sentence here to clarity with the audience that these are two independent samples for two different end goals. For example:

"Currently, we provides two samples with two different end goals. One shows case how the PIC-IoT board interacts with DPS. The other shows case IoT Plug and Play's benefits on the board. Depending on your end-goals, pick one sample to try out. The instruction below applies to both samples, the only different is at the "View PIC-IoT board telemetry on Azure IoT Explorer" step.

Note that the two samples a building on top of each other. Eventually, they will be merge into one".

2020-08-21 07:35 UTC, nkhuyent commented on README.md
> +Connect the device through Azure IoT Hub Device Provisioning to then connect to your IoT Hub.
Ok. let's rephrase this like so - "This is the primary sample of this guidance which shows case how to connect the PIC-IoT board to Azure IoT Hub through Device Provisioning Service. As the result, you can view the board telemetry on Azure IoT Explorer."

2020-08-21 07:35 UTC, nkhuyent commented on README.md
> +
I think we should add this paragraph to clarify: 

"This is the secondary sample that leverages the primary sample work to demonstrate how the PIC-IoT board can be benefits from new Azure offering called IoT Plug and Play. As the result, in addition to view the device telemetry, you can all the capabilities (such as its properties, telemetry, and commands) of the device as well. In short, the key enabled Azure offerings are IoT Hub, DPS, Azure IoT Explorer and IoT plug and Play.

To further understand what Plug and Play is, please see documentation [here](https://docs.microsoft.com/en-us/azure/iot-pnp/overview-iot-plug-and-play).

This sample uses the example interface [here](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/samples/Thermostat.json). "

2020-08-21 07:35 UTC, nkhuyent commented on README.md
> +
What do you think about moving the remaining of this session to be add the end of the "View PIC-IoT board telemetry on Azure IoT Explorer" session. And make this the sub session with title like " Addition instructions for AzureIotPnpDps.X sample" or something like that.

2020-08-21 21:03 UTC, danewalton-msft commented on README.md
> +## Prerequisites
I'll merge the two. Calling "Setup Instructions" -> "Prerequisites"

2020-08-21 21:30 UTC, danewalton-msft commented on README.md
> +Once the board is flashed (directions later), you can proceed to interact with the Plug and Play device using the Azure IoT Explorer. The following steps make it as seamless as possible.
No meant below. Clarified

2020-08-21 21:36 UTC, danewalton-msft commented on README.md
> +
updated a bit to closely fit what you are insinuating

2020-08-25 01:49 UTC, merged